---
title: "ONAQ_insitu"
author: "K Duffy"
date: "12/30/2019"
output: html_document
---
Steps: 
1) Pull the phenological and status intensity data from MOAB (native grass) and ONAQ (BRTE)
2) Store that data in a new Rdata frame
3) Make 1 plot of the data to understand what's 'there'



```{r}
library(tidyverse)
library(dplyr, quietly=T)
library(lubridate)


##pull all available data for a site from the NEON API

library(neonUtilities)
```
```{r}

## 
dpid <- as.character('DP1.10055.001') #phe data

pheDat <- loadByProduct(dpID="DP1.10055.001",
                        site = c("JORN"),
                        package = "basic",
                        check.size = FALSE)

# unlist all data frames
list2env(pheDat ,.GlobalEnv)

unique(phe_perindividual$scientificName)
#[1] "BRTE"  "ARTR2" "CETE5"
```

```{r}
# subset to cheatgrass individuals in both perindivual and statusintenstiy datasets
# dedupe
#fix this chunk
perind <- phe_perindividual%>%   # table with taxonID + location 
  select(-uid, -date)%>% 
  group_by(individualID)%>% 
  filter(taxonID=="PLJA")%>%
  ungroup()
```
```{r}
PLJA_instensity <- phe_statusintensity%>%  # table with in situ obsevations
  select(-uid)%>%
  group_by(individualID, date, phenophaseName) %>%
  filter(individualID%in%perind$individualID)%>%
  ungroup()
```

```{r}
# merge
grass_name <- left_join(obs, perind, by="individualID")

#lots of extraneous fields here. happy to help trim if needed. 
```

```{r}
cheatgrass_growth=BRTE_instensity%>%
  group_by(phenophaseName)%>%
  summarise(date_event=min(as.numeric(date)))
```

```{r}
magnitude_phenometrics_data=magnitude_phenometrics_data[order(magnitude_phenometrics_data$Start_Date), ]
p3 = plot_ly() %>%
  add_trace(
  data = magnitude_phenometrics_data,
  x = ~ Start_Date,
  y = ~ Proportion_Yes_Records,
  name = 'ONAQ CHeatgrass',
  showlegend = TRUE,
  type = 'scatter',
  mode = 'line')
p3
```
