---
title: "NSF Figs"
author: "K Duffy"
date: "12/28/2019"
output: html_document
---

PLots:
ONAQ:
```{r, silent=TRUE}
library(phenocamapi)
library(plotly)
library(phenocamr)
library(dplyr)
```

Let's start by pulling in a list of PhenoCam sites:



```{r}
phenos=get_phenos()
#and let's check the column names:
colnames(phenos)

rois=get_rois()
colnames(rois)
```


```{r}
ONAQ_rois=rois%>%
  filter(site=='NEON.D15.ONAQ.DP1.00042')
head(ONAQ_rois)

MOAB_rois=rois%>%
  filter(site=='NEON.D13.MOAB.DP1.00042')
head(MOAB_rois)
```
```{r}
# phenocamr::download_phenocam(
#   frequency = 3,
#   veg_type = 'GR',
#   roi_id = 1000,
#   site = 'NEON.D13.MOAB.DP1.00033',
#   phenophase = TRUE,
#   out_dir = "."
#   )

moab_df=get_pheno_ts('NEON.D13.MOAB.DP1.00033', 'GR', 1000, type='3day')

```


```{r}
# td <- phenophases("your_.csv",
#            internal = TRUE,
#            upper_thresh = 0.8)
df <- read.table("NEON.D15.ONAQ.DP1.00033_GR_1000_3day.csv", header = TRUE, sep = ",")
td <- read.table("NEON.D15.ONAQ.DP1.00033_GR_1000_3day_transition_dates.csv",
                 header = TRUE,
                 sep = ",")

fall <- td[td$direction == "falling" & td$gcc_value == "gcc_90",]
spring <- td[td$direction == "rising" & td$gcc_value == "gcc_90",]

df_moab <- read.table("NEON.D13.MOAB.DP1.00042_GR_1000_3day.csv", header = TRUE, sep = ",")
td_moab <- read.table("NEON.D13.MOAB.DP1.00042_GR_1000_3day_transition_dates.csv",
                 header = TRUE,
                 sep = ",")

fall_moab <- td_moab[td_moab$direction == "falling" & td_moab$gcc_value == "gcc_90",]
spring_moab <- td_moab[td_moab$direction == "rising" & td_moab$gcc_value == "gcc_90",]
```

```{r}
source('/Users/kdw223/Research/PostDoc/NEONCheatgrass/gcc_plot.R')
plot1 = gcc_plot(df, spring, fall, 'ONAQ Cheatgrass')
plot1
plot2=gcc_plot(df_moab, spring_moab, fall_moab, 'ONAQ Cheatgrass vs. MOAB Native Grass')
plot2
plot3=subplot(plot1, plot2, nrows=2)
plot3
```





```{r}
ONAQ_sh=get_pheno_ts(site='NEON.D15.ONAQ.DP1.00042', vegType='SH', roiID=1001, type='3day')
ONAQ_sh=ONAQ_sh[!is.na(gcc_90)]
ONAQ_sh$smoothed=smooth(ONAQ_sh$gcc_90)
ONAQ_gr=get_pheno_ts(site='NEON.D15.ONAQ.DP1.00042', vegType='GR', roiID=1000, type='3day')
ONAQ_gr=ONAQ_gr[!is.na(gcc_90)]
ONAQ_gr$smoothed=smooth(ONAQ_gr$gcc_90)
MOAB_gr=get_pheno_ts(site='NEON.D13.MOAB.DP1.00042', vegType='GR', roiID=1000, type='3day')
MOAB_gr=MOAB_gr[!is.na(gcc_90)]
MOAB_gr$smoothed=smooth(MOAB_gr$gcc_90)
MOAB_gr_un=get_pheno_ts(site='NEON.D13.MOAB.DP1.00033', vegType='GR', roiID=1000, type='3day')
MOAB_gr_un=MOAB_gr_un[!is.na(gcc_90)]
MOAB_gr_un$smoothed=smooth(MOAB_gr$gcc_90)
```

```{r}
p = plot_ly() %>%
  add_trace(
  data = ONAQ_sh,
  x = ~ as.Date(date),
  y = ~ smoothed,
  name = 'ONAQ Shrubs',
  showlegend = TRUE,
  type = 'scatter',
  mode = 'line', 
  name='PhenoCam GCC'
) %>%
    add_trace(
  data = ONAQ_gr,
  x = ~ as.Date(date),
  y = ~ smoothed,
  name = 'ONAQ Cheatgrass',
  showlegend = TRUE,
  type = 'scatter',
  mode = 'line'
) %>%
    add_trace(
  data = MOAB_gr,
  x = ~ as.Date(date),
  y = ~ smoothed,
  name = 'MOAB Native Grass',
  showlegend = TRUE,
  type = 'scatter',
  mode = 'line'
) 
p
```

```{r}
library(mosaic)

p2 = plot_ly() %>%
    add_trace(
  data = ONAQ_gr,
  x = ~ as.Date(date),
  y = ~ zscore(smoothed),
  name = 'ONAQ Cheatgrass',
  showlegend = TRUE,
  type = 'scatter',
  mode = 'marker'
) %>%
    add_trace(
  data = MOAB_gr,
  x = ~ as.Date(date),
  y = ~ zscore(smoothed),
  name = 'MOAB Native Grass',
  showlegend = TRUE,
  type = 'scatter',
  mode = 'marker'
) 
p2
```

```{r}
m <- loess(gcc_90 ~ as.numeric(date), data = ONAQ_gr)
```
```{r}
p <- plot_ly(ONAQ_gr, x = ~as.Date(date), color = I("black")) %>%
  add_markers(y = ~gcc_90, showlegend = FALSE) %>%
  add_lines(y = ~m$fitted,
            line = list(color = 'rgba(7, 164, 181, 1)'),
            name = "Loess Smoother") #%>%
  #add_ribbons(data = augment(m),
   #           ymin = ~.fitted - 1.96 * .se.fit,
    #          ymax = ~.fitted + 1.96 * .se.fit,
     #         line = list(color = 'rgba(7, 164, 181, 0.05)'),
      #        fillcolor = 'rgba(7, 164, 181, 0.2)',
       #       name = "Standard Error") %>%
  #layout(xaxis = list(title = 'Displacement (cu.in.)'),
   #      yaxis = list(title = 'Miles/(US) gallon'),
    #     legend = list(x = 0.80, y = 0.90))

p
```

```{r}
# phenocamr::download_phenocam(
#   frequency = 1,
#   veg_type = 'SH',
#   roi_id = 1001,
#   site = 'NEON.D15.ONAQ.DP1.00042',
#   phenophase = TRUE,
#   out_dir = "."
#   )
#phenocamr::download_phenocam(
 # frequency = 3,
  #veg_type = 'GR',
  #roi_id = 1000,
  #site = phenos$site[15],
  #phenophase = TRUE,
  #out_dir = "."
  #)

```

```{r}
# load the time series data but replace the csv filename with whatever you downloaded
df_sh <- read.table("~/Research/PostDoc/NEONCheatgrass/NEON.D15.ONAQ.DP1.00042_SH_1001_1day.csv", header = TRUE, sep = ",")

# read in the transition date file
td_sh <- read.table("~/Research/PostDoc/NEONCheatgrass/NEON.D15.ONAQ.DP1.00042_SH_1001_1day_transition_dates.csv",
                 header = TRUE,
                 sep = ",")
df_gr <- read.table("~/Research/PostDoc/NEONCheatgrass/NEON.D15.ONAQ.DP1.00042_GR_1000_1day.csv", header = TRUE, sep = ",")

# read in the transition date file
td_gr <- read.table("~/Research/PostDoc/NEONCheatgrass/NEON.D15.ONAQ.DP1.00042_GR_1000_1day_transition_dates.csv",
                 header = TRUE,
                 sep = ",")
```

```{r}
spring_sh <- td_sh[td_sh$direction == "rising" & td_sh$gcc_value == "gcc_90",]
fall_sh <- td_sh[td_sh$direction == "falling" & td_sh$gcc_value == "gcc_90",]
spring_gr <- td_gr[td_gr$direction == "rising" & td_gr$gcc_value == "gcc_90",]
fall_gr <- td_gr[td_gr$direction == "falling" & td_gr$gcc_value == "gcc_90",]
```
```{r}
p_sh = plot_ly() %>%
  add_trace(
  data = df_sh,
  x = ~ as.Date(date),
  y = ~ smooth_gcc_90,
  name = 'PhenoCam GCC Shrubs',
  showlegend = TRUE,
  type = 'scatter',
  mode = 'line'
) %>% add_markers(
  data= fall_gr, 
  x = ~ as.Date(fall_gr$transition_25, origin = "1970-01-01"),
  y = ~ fall_gr$threshold_25,
  type = 'scatter',
  mode = 'marker',
  name = '25% Threshold of Greenness')%>%
  add_trace(
  data = df_gr,
  x = ~ as.Date(date),
  y = ~ smooth_gcc_90,
  name = 'PhenoCam GCC Cheatgrass',
  showlegend = TRUE,
  type = 'scatter',
  mode = 'line')
# ) %>% add_markers(
#   data= fall_gr, 
#   x = ~ as.Date(fall_gr$transition_25, origin = "1970-01-01"),
#   y = ~ fall_gr$threshold_25,
#   type = 'scatter',
#   mode = 'marker',
#   name = '25% Threshold of Greenness')
                
p_sh
```

```{r}

gcc_plot = function(gcc, spring, fall, plot_title){
  unix = "1970-01-01"

  p = plot_ly(
    data = gcc,
    x = ~ date,
    y = ~ gcc_90,
    showlegend = FALSE,
    type = 'scatter',
    mode = 'markers' 
    #opacity=.5
  ) %>%
    add_trace(
      y = ~ smooth_gcc_90,
      mode = "lines",
      line = list(width = 2, color = "rgb(120,120,120)"),
      name = "Gcc loess fit",
      showlegend = TRUE
    ) %>%
    # SOS spring
    # 10%
    add_trace(
      data = spring,
      x = ~ as.Date(transition_10),
      y = ~ threshold_10,
      mode = "markers",
      type = "scatter",
      marker = list(color = "#7FFF00", symbol = "circle"),
      name = "SOS (10%)",
      showlegend = TRUE
    ) %>%
    add_segments(x = ~ as.Date(transition_10_lower_ci),
                 xend = ~ as.Date(transition_10_upper_ci),
                 # y = ~ 0,
                 # yend = ~ 1,
                 y = ~ threshold_10,
                 yend = ~ threshold_10,
                 line = list(color = "#7FFF00"),
                 name = "SOS (10%) - CI"
    ) %>%
    # 25 %
    add_trace(
      x = ~ as.Date(transition_25),
      y = ~ threshold_25,
      mode = "markers",
      type = "scatter",
      marker = list(color = "#66CD00", symbol = "square"),
      showlegend = TRUE,
      name = "SOS (25%)"
    ) %>%
    add_segments(x = ~ as.Date(transition_25_lower_ci),
                 xend = ~ as.Date(transition_25_upper_ci),
                 y = ~ threshold_25,
                 yend = ~ threshold_25,
                 line = list(color = "#66CD00"),
                 name = "SOS (25%) - CI"
    ) %>%
    # 50 %
    add_trace(
      x = ~ as.Date(transition_50),
      y = ~ threshold_50,
      mode = "markers",
      type = "scatter",
      marker = list(color = "#458B00", symbol = "diamond"),
      showlegend = TRUE,
      name = "SOS (50%)"
    ) %>%
    add_segments(x = ~ as.Date(transition_50_lower_ci),
                 xend = ~ as.Date(transition_50_upper_ci),
                 y = ~ threshold_50,
                 yend = ~ threshold_50,
                 line = list(color = "#458B00"),
                 name = "SOS (50%) - CI"
    ) %>%
    
    # EOS fall
    # 50%
    add_trace(
      data = fall,
      x = ~ as.Date(transition_50),
      y = ~ threshold_50,
      mode = "markers",
      type = "scatter",
      marker = list(color = "#FFB90F", symbol = "diamond"),
      showlegend = TRUE,
      name = "EOS (50%)"
    ) %>%
    add_segments(x = ~ as.Date(transition_50_lower_ci),
                 xend = ~ as.Date(transition_50_upper_ci),
                 y = ~ threshold_50,
                 yend = ~ threshold_50,
                 line = list(color = "#FFB90F"),
                 name = "EOS (50%) - CI"
    ) %>%
    # 25 %
    add_trace(
      x = ~ as.Date(transition_25),
      y = ~ threshold_25,
      mode = "markers",
      type = "scatter",
      marker = list(color = "#CD950C", symbol = "square"),
      showlegend = TRUE,
      name = "EOS (25%)"
    ) %>%
    add_segments(x = ~ as.Date(transition_25_lower_ci),
                 xend = ~ as.Date(transition_25_upper_ci),
                 y = ~ threshold_25,
                 yend = ~ threshold_25,
                 line = list(color = "#CD950C"),
                 name = "EOS (25%) - CI"
    ) %>%
    # 10 %
    add_trace(
      x = ~ as.Date(transition_10),
      y = ~ threshold_10,
      mode = "markers",
      marker = list(color = "#8B6508", symbol = "circle"),
      showlegend = TRUE,
      name = "EOS (10%)"
    ) %>%
    add_segments(x = ~ as.Date(transition_10_lower_ci),
                 xend = ~ as.Date(transition_10_upper_ci),
                 y = ~ threshold_10,
                 yend = ~ threshold_10,
                 line = list(color = "#8B6508"),
                 name = "EOS (10%) - CI"
    )%>% 
    layout(title=plot_title)
  return (p)
}

```


```{r}
grass = gcc_plot(df_gr, spring_gr, fall_gr, 'ONAQ Cheatgrass')
grass
```

```{r}
max_val_grass=df_gr%>%
  group_by(year)%>%
  summarise(mx_val=max(smooth_gcc_mean))%>%
  arrange(mx_val)
```

```{r}
mx_dates_grass=df_gr%>%
  arrange_(~ desc(smooth_gcc_mean)) %>%
  group_by_(~ year) %>%
  slice(1:5)
```

```{r}
max_val_shrubs=df_sh%>%
  group_by(year)%>%
  summarise(mx_val=max(smooth_gcc_mean))%>%
  arrange(mx_val)
```

```{r}
mx_dates_shrubs=df_sh%>%
  arrange_(~ desc(smooth_gcc_mean)) %>%
  group_by_(~ year) %>%
  slice(1:5)
```

```{r}
mx_dates_grass%>%
  filter(year==c('2017', '2018', '2019'))%>%
  summarise(sample_date=mean(doy))
```
```{r}
mx_dates_shrubs%>%
  summarise(sample_date=mean(doy))
```
